name: Fetch my GD-Account
on: 
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch: 
jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Fetch Da File :P
        run: |
          curl -X POST https://www.boomlings.com/database/getGJUserInfo20.php -d "secret=Wmfd2893gb7&targetAccountID=19635188" -A "" -o myGDProfile.txt

      - name: Commit to it :D
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add myGDProfile.txt
          git commit -m "Update myProfile" || echo "No changes"
          git push
